### ISSUE TITLE
Jetstream and Vuexy

### ISSUE THREAD

**Issue by serobalino** [pixinvent/jetstrap-vuexy#1]
I want a vuexy installation with jetstream, I followed all the steps and it doesn't work.
first it asked me for a 'panels' directory inside resources I copied it from the template folder but it was useless now the [dashboard, welcome, login, register ] view does not exist and therefore the project is useless the idea would be to replace all the default Laravel styles and use Vuexy with vue to make it work perfectly, but no Help please.
![Screenshot 2022-01-18 at 15-51-14 🧨 View  dashboard  not found ](https://user-images.githubusercontent.com/14143663/150016659-73493905-4f5c-42b6-9dd3-5cbd0f7bac02.png)

**Comment by alokVishu** [comment]
Hello @serobalino,

Please raise a support ticket at https://pixinvent.ticksy.com/
 
~Regards
