### ISSUE TITLE
Loading PostCSS "tailwindcss" plugin failed: Cannot find module 'tailwindcss'

### ISSUE THREAD

**Issue by masadi** [pixinvent/jetstrap-vuexy#2]
ERROR in ./resources/scss/base/plugins/charts/chart-apex.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleError: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "tailwindcss" plugin failed: Cannot find module 'tailwindcss'
Require stack:
- d:\WinNMP\WWW\erapor6\node_modules\postcss-loader\dist\utils.js
- d:\WinNMP\WWW\erapor6\node_modules\postcss-loader\dist\index.js
- d:\WinNMP\WWW\erapor6\node_modules\postcss-loader\dist\cjs.js
- d:\WinNMP\WWW\erapor6\node_modules\webpack\lib\ProgressPlugin.js
- d:\WinNMP\WWW\erapor6\node_modules\webpack\lib\index.js
- d:\WinNMP\WWW\erapor6\node_modules\webpack-cli\lib\webpack-cli.js
- d:\WinNMP\WWW\erapor6\node_modules\webpack-cli\lib\bootstrap.js
- d:\WinNMP\WWW\erapor6\node_modules\webpack-cli\bin\cli.js
- d:\WinNMP\WWW\erapor6\node_modules\webpack\bin\webpack.js

How to fix it?

**Comment by chrisperman** [comment]
I am getting this exact issue, was there a fix?
